#!/usr/bin/env php
<?php
spl_autoload_extensions(".php");
spl_autoload_register(function($class) {
    $file = __DIR__ . '/'  . str_replace('\\', '/', $class). '.php';
    if (file_exists(stream_resolve_include_path($file))) include($file);
});
require 'vendor/autoload.php';

$commands = include "Commands/registry.php";

// 第2引数は実行するコマンドです。
$inputCommand = $argv[1];

// PHPでインスタンス化できるコマンドのクラス名をすべて調べます。
foreach ($commands as $commandClass) {
    $alias = $commandClass::getAlias();

    if($inputCommand === $alias){
        if(in_array('--help',$argv)){
            fwrite(STDOUT, $commandClass::getHelp());
            exit(0);
        }
        else{
            $command = new $commandClass();
            $result = $command->execute();
            exit($result);
        }
    }
}

fwrite(STDOUT,"Failed to run any commands\n");
